apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: coach-app
type: Opaque
stringData:
  username: admin
  password: wattrelos_dev_2025
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: coach-app
type: Opaque
stringData:
  jwt-secret: wattrelos_fc_secret_key_2025_local_dev
  mongodb-uri: mongodb://admin:wattrelos_dev_2025@mongodb-service:27017/coach_app?authSource=admin
