apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coach-app-preprod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: coach-app
  
  source:
    repoURL: https://gitlab.com/bouzakri.badr/coach_app.git
    targetRevision: main
    path: environments/preprod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: coach-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
